config globals 'globals'
	option mmx_mask '0x3F00'

config interface 'wan'
	option enabled '1'
	option family 'ipv4'
	option reliability '1'
	option count '1'
	option timeout '2'
	option interval '10'
	option down '3'
	option up '3'
	list track_ip '223.5.5.5'
	list track_ip '119.29.29.29'
	list track_ip '114.114.114.114'

config interface 'usb'
	option enabled '0'
	option family 'ipv4'
	option reliability '1'
	option count '1'
	option timeout '2'
	option interval '60'
	option down '2'
	option up '2'
	list track_ip '223.5.5.5'

config member 'wan_m1_w3'
	option interface 'wan'
	option metric '1'
	option weight '3'

config member 'usb_m1_w3'
	option interface 'usb'
	option metric '1'
	option weight '3'

config policy 'campus_only'
	option last_resort 'unreachable'
	list use_member 'wan_m1_w3'

config policy 'usb_only'
	option last_resort 'unreachable'
	list use_member 'usb_m1_w3'

config rule 'campus_portal'
	option dest_ip '10.2.5.251'
	option use_policy 'campus_only'

config rule 'https'
	option sticky '1'
	option dest_port '443'
	option proto 'tcp'
	option use_policy 'campus_only'

config rule 'default_rule'
	option dest_ip '0.0.0.0/0'
	option use_policy 'campus_only'